# Generated by Django 5.2.8 on 2025-11-26 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('given_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('profile_description', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'USER',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('required_caregiving_type', models.CharField(max_length=100)),
                ('other_requirements', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateField()),
            ],
            options={
                'db_table': 'JOB',
            },
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('caregiver_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('caregiving_type', models.CharField(max_length=100)),
                ('hourly_rate', models.FloatField()),
            ],
            options={
                'db_table': 'CAREGIVER',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('house_rules', models.TextField(blank=True, null=True)),
                ('dependent_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MEMBER',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('pk', models.CompositePrimaryKey('caregiver_user_id', 'job_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('date_applied', models.DateField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job')),
                ('caregiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caregiver')),
            ],
            options={
                'db_table': 'JOB_APPLICATION',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('member_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.member')),
                ('house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ADDRESS',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='member_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('work_hours', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('caregiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.caregiver')),
                ('member_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
            ],
            options={
                'db_table': 'APPOINTMENT',
            },
        ),
    ]
